# Pages placed under these sections will be shown on homepage and archive page.
mainSections:
  - "post"
# Output page's full content in RSS.
rssFullContent: true
favicon: "/favicon.png"

footer:
  since: 2025
  customText: ""

dateFormat:
  published: 02 Jan 2006
  lastUpdated: 02 Jan 2006 15:04 MST

sidebar:
  emoji: ""
  subtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  avatar:
    enabled: true
    local: true
    src: "img/avatar.png"

article:
  headingAnchor: false
  math: false
  readingTime: true
  license:
    enabled: true
    default: "Licensed under CC BY-NC-SA 4.0"

# Widgets
widgets:
  homepage:
    - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 10
    - type: "tag-cloud"
      params:
        limit: 10
  page:
    - type: "toc"

opengraph:
  twitter:
    site: ""
    card: "summary_large_image"

defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""

colorScheme:
  toggle: true
  default: "light"

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

paginate: 5